### PR TITLE
Support init with Runtime

### PR DESCRIPTION
**Pull request by evshary**
@PLeVasseur As mentioned in #42, I created a constructor to accept Runtime. It seems like the only way to create Runtime is to use plugins, so I can't write tests for it. Let me know if you have any issues while using it.

### CODE REVIEW

**Comment by evshary** [comment]
@PLeVasseur By the way, I'm not sure why I can't request you as a reviewer on GitHub...

**Comment by PLeVasseur** [comment]
I think you can only request committers, and while it got approved through Eclipse I am probably not yet a committer on the project on GitHub.

Just my guess tho 🤔

**Review by PLeVasseur — APPROVED** [review]
Hey @evshary -- this works! Got it working when run inside of a Zenoh Plugin.

Can we merge it so I can rely on main for the demo?

There is a part of me that wonders... is there no way to create a Zenoh Runtime outside of being a Plugin? I feel like it should be possible in order to unit test all the Plugin stuff in mainline Zenoh? :thinking:

**Comment by evshary** [comment]
@PLeVasseur Sure. I took a quick look at the unit test. It seems like unit test focuses on other functions (not the full initialization). There is also an example plugin, and I guess it kind of covers the test of initialization.

**Pull request merged**
